# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-github-oidc-role
  description: This component is responsible for creating IAM roles for GitHub Actions to assume
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component



